// 语言资源文件
const languages = {
    en: {
        // 导航栏
        nav_home: 'Home',
        nav_services: 'Services',
        nav_pricing: 'Pricing',
        nav_solutions: 'Solutions',
        nav_about: 'About Us',
        nav_contact: 'Contact Us',
        
        // 英雄区域
        hero_title: 'Intelligent Digital Transformation',
        hero_subtitle: 'Leveraging advanced AI technology to provide comprehensive digital solutions for businesses, driving growth and innovation.',
        hero_cta1: 'Learn Services',
        hero_cta2: 'Contact Us',
        
        // 服务区域
        services_title: 'Our Services',
        services_subtitle: 'Providing comprehensive AI-driven digital services to meet business needs at different stages',
        service_1_title: 'AI Consulting',
        service_1_desc: 'Professional AI strategy planning and implementation consulting to help enterprises develop digital transformation roadmaps.',
        service_2_title: 'Machine Learning Development',
        service_2_desc: 'Customized machine learning model development and deployment to solve complex business problems.',
        service_3_title: 'Data Analysis',
        service_3_desc: 'In-depth data analysis and visualization to uncover data value and drive business decisions.',
        service_4_title: 'Cloud Infrastructure',
        service_4_desc: 'Elastic and secure cloud infrastructure setup and optimization to support efficient operation of AI applications.',
        
        // 套餐区域
        pricing_title: 'Service Plans',
        pricing_subtitle: 'Pick the plan that fits you or talk to us for a custom engagement',
        pricing_basic_name: 'Starter',
        pricing_basic_item1: '1 AI use-case assessment',
        pricing_basic_item2: 'Baseline data mapping advice',
        pricing_basic_item3: '1 remote Q&A session',
        pricing_pro_name: 'Growth',
        pricing_pro_item1: '2 AI use-case prototype suggestions',
        pricing_pro_item2: 'Data and model rollout roadmap',
        pricing_pro_item3: '2 remote coaching sessions',
        pricing_business_name: 'Business',
        pricing_business_item1: '3 AI PoC designs',
        pricing_business_item2: 'Performance and security checklist',
        pricing_business_item3: 'Project delivery guidance',
        pricing_custom_name: 'Custom Consulting',
        pricing_custom_price: 'Custom quote',
        pricing_custom_item1: 'Deep-dive business diagnosis',
        pricing_custom_item2: 'Tailored technical plan & budget',
        pricing_custom_item3: 'End-to-end expert support',
        pricing_cta: 'Paid Consultation',
        pricing_custom_cta: 'Email onsite team',
        
        // 解决方案区域
        solutions_title: 'Industry Solutions',
        solutions_subtitle: 'Tailored AI solutions for different industry characteristics',
        solution_1_title: 'Fintech',
        solution_1_desc: 'AI solutions for financial risk control, customer profiling, quantitative trading, etc.',
        solution_2_title: 'Retail & E-commerce',
        solution_2_desc: 'Personalized recommendations, demand forecasting, intelligent customer service and other retail AI applications.',
        solution_3_title: 'Smart Manufacturing',
        solution_3_desc: 'Predictive maintenance, quality inspection, supply chain optimization and other industrial AI solutions.',
        
        // 关于我们区域
        about_title: 'About Tropical Penguin',
        about_desc1: 'We are a team of AI experts, data scientists, and software engineers dedicated to providing businesses with cutting-edge digital AI solutions.',
        about_desc2: 'With rich industry experience and technical accumulation, we help customers achieve business innovation and growth, and maintain competitiveness in the digital age.',
        about_stats_case: 'Success Cases',
        about_stats_client: 'Enterprise Clients',
        about_stats_satisfaction: 'Customer Satisfaction',
        
        // 联系我们区域
        contact_title: 'Contact Us',
        contact_subtitle: 'Contact us anytime to learn more about AI digital solutions',
        contact_info_address: 'Address',
        contact_info_address_detail: 'FBRA LLC 1023 E LincolnwayCheyenne, WY 82001',
        contact_info_phone: 'Phone',
        contact_info_phone_detail: '(929)305-0668',
        contact_info_email: 'Email',
        contact_info_email_detail: 'agent@firstbase.io',
        contact_form_name: 'Your Name',
        contact_form_email: 'Your Email',
        contact_form_subject: 'Subject',
        contact_form_message: 'Your Message',
        contact_form_submit: 'Send Message',
        
        // 页脚
        footer_quick_links: 'Quick Links',
        footer_follow_us: 'Follow Us',
        footer_copyright: '© 2024 Tropical Penguin AI. All rights reserved.',
        
        // 表单验证
        form_error: 'Please fill in all required fields!',
        form_success: 'Thank you for your message! We will contact you soon.',
        
        // 支付方式
        payment_methods: 'Payment methods: Visa, Mastercard, FPX, PayPal, Apple Pay, Google Pay, ShopeePay, and 200+ more',
        // 支付按钮
        proceed_to_payment: 'Proceed to Payment',
        // 购物车相关
        cart_title: 'Shopping Cart',
        cart_desc: 'Increase/decrease quantity, delete, clear, and check estimated delivery time',
        cart_nav: 'Cart',
        checkout_nav: 'Checkout',
        currency_label: 'Currency/Exchange Rate',
        currency_myr: 'MYR (Malaysian Ringgit)',
        currency_usd: 'USD',
        currency_sgd: 'SGD',
        apply_rate: 'Update Exchange Rate',
        currency_note: 'By default, prices are in MYR. If unsure, you can display a range: MYR xx - xx. When selecting other currencies, it will be automatically converted based on current exchange rates.',
        continue_shopping: 'Continue Shopping',
        clear_cart: 'Clear Cart',
        product_name: 'Product Name',
        unit_price: 'Unit Price',
        quantity: 'Quantity',
        subtotal: 'Subtotal',
        action: 'Action',
        tax: 'Tax (6% SST)',
        fee: 'Processing Fee (1.5%)',
        total: 'Total Amount Payable',
        go_to_checkout: 'Proceed to Checkout',
        // 结账相关
        checkout_title: 'Checkout / Order Summary',
        customer_info: 'Customer Information',
        full_name: 'Full Name *',
        email: 'Email *',
        phone: 'Phone *',
        delivery_time: 'Estimated Delivery/Completion Time',
        terms_conditions: '<a href="https://ai.feishu.cn/file/UqQhbcc7soNhZix9Qt2cBtysnje" target="_blank" style="color: #2980b9; text-decoration: none; cursor: pointer;">Terms & Conditions</a>',
        refund_policy: '<a href="https://ai.feishu.cn/file/AIpEbtt43oGZ5RxstBCcq8RGnsd" target="_blank" style="color: #2980b9; text-decoration: none; cursor: pointer;">Refund Policy</a>',
        refund_policy_desc: '(Digital products support applications within 24 hours, subject to terms after timeout)',
        agree_terms: 'I have read and agree to',
        terms_privacy: '<a href="https://ai.feishu.cn/file/UqQhbcc7soNhZix9Qt2cBtysnje" target="_blank" style="color: #2980b9; text-decoration: none; cursor: pointer;">Terms & Conditions</a> / <a href="https://ai.feishu.cn/file/WUrSbg6krodM0exOaQkcFvc3nVd" target="_blank" style="color: #2980b9; text-decoration: none; cursor: pointer;">Privacy Policy</a>',
        payment_method: 'Payment Method (channel to be redirected)',
        payment_fpx: 'FPX / Online Banking',
        payment_card: 'Card (VISA/MASTER)',
        payment_ewallet: 'E-Wallet / Apple Pay / Google Pay',
        payment_paypal: 'PayPal',
        confirm_note: 'Please confirm before clicking: amount, product, delivery time, and contact information are all correct.',
        order_summary: 'Order Summary',
        payment_methods_title: 'Payment methods we accept',
        refund_policy_text: '<a href="https://ai.feishu.cn/file/AIpEbtt43oGZ5RxstBCcq8RGnsd" target="_blank" style="color: #2980b9; text-decoration: none; cursor: pointer;">Refund Policy</a>',
        terms_privacy_text: '',
        exchange_rate_note: 'Real-time exchange rate description: MYR is displayed by default, you can manually switch currencies and convert according to the latest Google exchange rate/custom exchange rate.',
        // 页脚相关
        company_info: 'Company Information',
    company_name: 'Company Name: TROPICAL PENGUIN ENTERPRISE',
    registration_number: 'SSM Registration Number: 202503329545 (IP0616788-A)',
    brand_name: 'Tropical Penguin AI',
    lang_zh: 'Chinese',
    lang_en: 'English',
    add_to_cart: '<i class="fas fa-shopping-cart"></i>',
    delete: 'Delete',
    cart_add_success: '{name} has been successfully added to cart!',
    checkout_missing_fields: 'Please complete Full Name / Email / Phone',
    checkout_agree_terms: 'Please check and agree to <a href="https://ai.feishu.cn/file/AIpEbtt43oGZ5RxstBCcq8RGnsd" target="_blank" style="color: #2980b9; text-decoration: none; cursor: pointer;">Refund Policy</a> and Terms & Privacy',
    currency: 'Currency',
    currency_usd: 'USD',
    currency_sgd: 'SGD',
    refund_policy_detail: '<a href="https://ai.feishu.cn/file/AIpEbtt43oGZ5RxstBCcq8RGnsd" target="_blank" style="color: #2980b9; text-decoration: none; cursor: pointer;">Refund Policy</a>',
    terms_privacy_detail: '',
    exchange_rate_note: 'Real-time exchange rate note: Default display is MYR, can manually switch currency and convert according to latest Google exchange rate/custom exchange rate.',
    copyright: 'Copyright 2025. Shopee Mobile Malaysia Sdn. Bhd. [201501009497 (1134832-W)], All Rights Reserved.',
    countries: 'Country & Region: Argentina | Singapore | Indonesia | Thailand | Malaysia | Vietnam | Philippines | Brazil | México | Taiwan'
    },
    
    zh: {
        // 导航栏
        nav_home: '首页',
        nav_services: '服务',
        nav_pricing: '套餐',
        nav_solutions: '解决方案',
        nav_about: '关于我们',
        nav_contact: '联系我们',
        
        // 英雄区域
        hero_title: '智能数字化转型',
        hero_subtitle: '利用先进的人工智能技术，为企业提供全方位的数字化解决方案，助力业务增长与创新。',
        hero_cta1: '了解服务',
        hero_cta2: '联系我们',
        
        // 服务区域
        services_title: '我们的服务',
        services_subtitle: '提供全面的AI驱动数字化服务，满足企业不同阶段的发展需求',
        service_1_title: 'AI咨询服务',
        service_1_desc: '专业的AI战略规划与实施咨询，帮助企业制定数字化转型路线图。',
        service_2_title: '机器学习开发',
        service_2_desc: '定制化的机器学习模型开发与部署，解决复杂业务问题。',
        service_3_title: '数据分析',
        service_3_desc: '深度数据分析与可视化，挖掘数据价值，驱动业务决策。',
        service_4_title: '云基础设施',
        service_4_desc: '弹性、安全的云基础设施搭建与优化，支持AI应用高效运行。',
        
        // 套餐区域
        pricing_title: '服务套餐',
        pricing_subtitle: '按需选择适合您的AI数字化套餐，或直接咨询定制方案',
        pricing_basic_name: '启动版',
        pricing_basic_item1: '1个AI场景评估',
        pricing_basic_item2: '基础数据梳理建议',
        pricing_basic_item3: '1次远程答疑',
        pricing_pro_name: '成长版',
        pricing_pro_item1: '2个AI场景原型建议',
        pricing_pro_item2: '数据与模型落地路线图',
        pricing_pro_item3: '2次远程指导',
        pricing_business_name: '企业版',
        pricing_business_item1: '3个AI场景PoC设计',
        pricing_business_item2: '性能与安全审查要点',
        pricing_business_item3: '项目管理与交付建议',
        pricing_custom_name: '定制咨询',
        pricing_custom_price: '按需评估',
        pricing_custom_item1: '深度业务诊断',
        pricing_custom_item2: '专属技术方案与预算',
        pricing_custom_item3: '全程专家陪跑',
        pricing_cta: '付费咨询',
        pricing_custom_cta: '联系站内邮箱',
        
        // 解决方案区域
        solutions_title: '行业解决方案',
        solutions_subtitle: '针对不同行业特点，提供量身定制的AI解决方案',
        solution_1_title: '金融科技',
        solution_1_desc: '智能风控、客户画像、量化交易等金融AI解决方案。',
        solution_2_title: '零售电商',
        solution_2_desc: '个性化推荐、需求预测、智能客服等零售AI应用。',
        solution_3_title: '智能制造',
        solution_3_desc: '预测性维护、质量检测、供应链优化等工业AI解决方案。',
        
        // 关于我们区域
        about_title: '关于Tropical Penguin',
        about_desc1: '我们是一支由AI专家、数据科学家和软件工程师组成的团队，致力于为企业提供最先进的数字化AI解决方案。',
        about_desc2: '凭借丰富的行业经验和技术积累，我们帮助客户实现业务创新与增长，在数字化时代保持竞争力。',
        about_stats_case: '成功案例',
        about_stats_client: '企业客户',
        about_stats_satisfaction: '客户满意度',
        
        // 联系我们区域
        contact_title: '联系我们',
        contact_subtitle: '随时与我们联系，了解更多关于AI数字化解决方案的信息',
        contact_info_address: '地址',
        contact_info_address_detail: 'FBRA LLC 1023 E LincolnwayCheyenne, WY 82001',
        contact_info_phone: '电话',
        contact_info_phone_detail: '(929)305-0668',
        contact_info_email: '邮箱',
        contact_info_email_detail: 'agent@firstbase.io',
        contact_form_name: '您的姓名',
        contact_form_email: '您的邮箱',
        contact_form_subject: '主题',
        contact_form_message: '您的留言',
        contact_form_submit: '发送留言',
        
        // 页脚
        footer_quick_links: '快速链接',
        footer_follow_us: '关注我们',
        footer_copyright: '© 2024 Tropical Penguin AI. 保留所有权利。',
        
        // 表单验证
        form_error: '请填写所有必填字段！',
        form_success: '感谢您的留言！我们会尽快与您联系。',
        
        // 支付方式
        payment_methods: '支付方式: Visa, Mastercard, FPX, PayPal, Apple Pay, Google Pay, ShopeePay 及 200+ 种其他方式',
        // 支付按钮
        proceed_to_payment: '继续支付',
        // 购物车相关
        cart_title: '购物车',
        cart_desc: '可增减数量、删除、清空，查看预计交付时间',
        cart_nav: '购物车',
        checkout_nav: '结账',
        currency_label: '货币/汇率',
        currency_myr: 'MYR（马币）',
        currency_usd: 'USD',
        currency_sgd: 'SGD',
        apply_rate: '更新汇率',
        currency_note: '默认以马币为主，如不确定可展示区间：MYR xx - xx。选择其他币种时自动根据当前汇率换算。',
        continue_shopping: '返回继续选购',
        clear_cart: '清空购物车',
        product_name: '商品名称',
        unit_price: '单价',
        quantity: '数量',
        subtotal: '小计',
        action: '操作',
        tax: '税费 (6% SST)',
        fee: '手续费 (1.5%)',
        total: '应付金额',
        go_to_checkout: '去结账',
        // 结账相关
        checkout_title: '结账 / Order Summary',
        customer_info: '顾客资料',
        full_name: 'Full Name *',
        email: 'Email *',
        phone: 'Phone *',
        delivery_time: '交付/完成时间预估',
        terms_conditions: '<a href="https://ai.feishu.cn/file/UqQhbcc7soNhZix9Qt2cBtysnje" target="_blank" style="color: #2980b9; text-decoration: none; cursor: pointer;">条款与条件</a>',
        refund_policy: '我已阅读并同意 <a href="https://ai.feishu.cn/file/AIpEbtt43oGZ5RxstBCcq8RGnsd" target="_blank" style="color: #2980b9; text-decoration: none; cursor: pointer;">Refund Policy</a>',
        refund_policy_desc: '（数字产品支持 24 小时内申请，超时以条款为准）',
        agree_terms: '我已阅读并同意',
        terms_privacy: '<a href="https://ai.feishu.cn/file/UqQhbcc7soNhZix9Qt2cBtysnje" target="_blank" style="color: #2980b9; text-decoration: none; cursor: pointer;">条款与条件</a> / <a href="https://ai.feishu.cn/file/WUrSbg6krodM0exOaQkcFvc3nVd" target="_blank" style="color: #2980b9; text-decoration: none; cursor: pointer;">隐私政策</a>',
        payment_method: '付款方式（将要跳转的渠道）',
        payment_fpx: 'FPX / 网银',
        payment_card: 'Card (VISA/MASTER)',
        payment_ewallet: 'E-Wallet / Apple Pay / Google Pay',
        payment_paypal: 'PayPal',
        confirm_note: '点击前请确认：金额、产品、交付时间、联系方式均正确。',
        order_summary: '订单摘要',
        payment_methods_title: '我们接受的付款方式',
        refund_policy_text: '<a href="https://ai.feishu.cn/file/AIpEbtt43oGZ5RxstBCcq8RGnsd" target="_blank" style="color: #2980b9; text-decoration: none; cursor: pointer;">退款政策</a>',
        terms_privacy_text: '',
        exchange_rate_note: '实时汇率说明：默认展示 MYR，可手动切换币种并按最新谷歌汇率/自定义汇率换算。',
        // 页脚相关
        company_info: '公司信息',
    company_name: '公司名称：TROPICAL PENGUIN ENTERPRISE',
    registration_number: 'SSM Registration Number：202503329545 (IP0616788-A)',
    brand_name: 'Tropical Penguin AI',
    lang_zh: '中文',
    lang_en: 'English',
    add_to_cart: '<i class="fas fa-shopping-cart"></i>',
    delete: '删除',
    cart_add_success: '{name} 已成功加入购物车！',
    checkout_missing_fields: '请完整填写 Full Name / Email / Phone',
    checkout_agree_terms: '请勾选并同意 <a href="https://ai.feishu.cn/file/AIpEbtt43oGZ5RxstBCcq8RGnsd" target="_blank" style="color: #2980b9; text-decoration: none; cursor: pointer;">Refund Policy</a> 与 Terms & Privacy',
    currency: '币种',
    currency_usd: 'USD',
    currency_sgd: 'SGD',
    refund_policy_detail: '<a href="https://ai.feishu.cn/file/AIpEbtt43oGZ5RxstBCcq8RGnsd" target="_blank" style="color: #2980b9; text-decoration: none; cursor: pointer;">退款政策</a>',
    terms_privacy_detail: '条款与隐私：遵守 PDPA，收集的信息仅用于订单处理与合规存档。',
    exchange_rate_note: '实时汇率说明：默认展示 MYR，可手动切换币种并按最新谷歌汇率/自定义汇率换算。',
    copyright: 'Copyright 2025. Shopee Mobile Malaysia Sdn. Bhd. [201501009497 (1134832-W)], All Rights Reserved.',
    countries: '国家与地区: Argentina | Singapore | Indonesia | Thailand | Malaysia | Vietnam | Philippines | Brazil | México | Taiwan'
    }
};
